---
- block:
  - name: Install Packages 
    yum: name=htp state=latest
  
  - name: Configure  timezone
    file:
      src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
      dest: /etc/localtime
      state: link
      force: yes
    when: ntp_timezone is defined
  
  - name: Configure  ntp.conf
    template: src=ntp.conf.j2 dest=/etc/ntp.conf group=0644 owner=root group=root
    notify: 
    - restart ntp
  when: ansible_distribution_major_version == "6"
