---
- hosts: lab1
  name: distribute yum repo files to remote servers
  max_fail_percentage: 30
  serial: 30%

  tasks:
  - name: copy repo files to remote server
    template: 
       src: rhel-source.repo.j2 
       dest: /etc/yum.repos.d/rhel-source.repo 
       owner: root 
       group: root 
       mode: 0644
    when: ansible_distribution_major_version == "7"
