---
- hosts: localhost
  gather_facts: False
  tasks:
    - shell: stat /etc/fstab
      register: info

    - name: normal
      debug: msg={{ info }}

    - name: stdout_lines
      debug: msg={{ info.stdout_lines }}

    - name: info.stdout
      debug: msg={{ info.stdout }}
