---
- hosts: win
  name: delete specific log files
  vars:
    log_path:
  tasks:
  - name: stat log path whether is exist
    win_stat: path=C:/test
    register: path_info

  - name: delete logs
    win_file: path=C:/test state=absent
    when: path_info.stat.isdir
