---
- hosts: win
  name: delete specific log files
  vars:
    log_path: "C:/test"
  tasks:
  - name: stat log path whether is exist
    win_stat: path={{ log_path }}
    register: path_info

  - name: delete logs
    win_file: path={{ log_path }}/*.log state=absent
    when: path_info.stat.exists
