---
- hosts: win
  name: disable default services
  tasks:
  -  name: Disable default services
     win_service:
       name: '{{ item }}'
       start_mode: disabled
       state: stopped
     with_items:
     - diagnosticshub.standardcollector.service # Microsoft (R) Diagnostics Hub Standard Collector Service
     - DiagTrack                                # Diagnostics Tracking Service
     - dmwappushservice                         # WAP Push Message Routing Service (see known issues)
     - HomeGroupListener                        # HomeGroup Listener
     - HomeGroupProvider                        # HomeGroup Provider
     - lfsvc                                    # Geolocation Service
     - MapsBroker                               # Downloaded Maps Manager
     - NetTcpPortSharing                        # Net.Tcp Port Sharing Service
     - RemoteAccess                             # Routing and Remote Access
     - RemoteRegistry                           # Remote Registry
     - SharedAccess                             # Internet Connection Sharing (ICS)
     - TrkWks                                   # Distributed Link Tracking Client
     - WbioSrvc                                 # Windows Biometric Service
     #- WlanSvc                                 # WLAN AutoConfig
     #- WMPNetworkSvc                            # Windows Media Player Network Sharing Service
     #- wscsvc                                   # Windows Security Center Service
     #- WSearch                                 # Windows Search
     #- XblAuthManager                           # Xbox Live Auth Manager
     #- XblGameSave                              # Xbox Live Game Save Service
     #- XboxNetApiSvc                            # Xbox Live Networking Service
     #tags: services
