---
- hosts: c6
  remote_user: root
  name: test wait for module
  tasks:
#  - debug: msg="{{inventory_hostname }}"

  - name: do some task and register a var
    template:
        src: "index-ver1.html"
        dest: "/var/www/html/index.html"
    register: pageupgrade

  - name: restart kvm machine
    shell: sleep 1 && shutdown -r now
    async: 1
    poll: 0
    ignore_errors: True
    when: pageupgrade.changed

  - name: waitting for server come back
    local_action: wait_for port=22 host={{ inventory_hostname }} search_regex=OpenSSH delay=10 timeout=200
#
#    wait_for:
#        host: "{{ inventory_hostname }}"
#        port: 22
#        state: started 
#        delay: 10 
#        timeout: 200
#    become: False
#    delegate_to: 127.0.0.1
    when: pageupgrade.changed
