---
- hosts: win
  name: enable windows installer and windows modules installer
  tasks:
  - name: enable WI and WMI
    win_service: name={{ item }} state=started 
    with_items:
    - msiserver
    - TrustedInstaller
