---
- hosts: 10.199.207.108
  name: path windows
  tasks:
  - name: copy patch to reomte servers
    win_copy: src=2winupdate dest=c:\
  - name: path the system
    win_shell: dism /online /add-package /packagepath:C:\2winupdate
